#!/usr/bin/env python3
"""
Shader Compilation Script
Converts shader source files (.glsl, .vert, .frag) into C++ header files
Supports multiple graphics backends (OpenGL, Vulkan, Metal, WebGL, DirectX)
Handles large shaders by splitting them to avoid C++ string literal size limits
"""

import os
import sys
from pathlib import Path

# Maximum lines per string literal chunk (to avoid C++ 16KB limit)
MAX_LINES_PER_CHUNK = 200

def split_shader_into_chunks(source_lines, max_lines=MAX_LINES_PER_CHUNK):
    """Split shader source into chunks to avoid C++ string literal size limits"""
    chunks = []
    current_chunk = []
    
    for line in source_lines:
        current_chunk.append(line)
        if len(current_chunk) >= max_lines:
            chunks.append(current_chunk)
            current_chunk = []
    
    if current_chunk:
        chunks.append(current_chunk)
    
    return chunks if len(chunks) > 1 else [source_lines]

def generate_shader_header(shader_base_dir, output_file):
    """Generate a C++ header with all shader sources organized by backend"""
    
    # Supported backends and their directories
    backends = ['OpenGL', 'Vulkan', 'Metal', 'WebGL', 'DirectX11', 'DirectX12']
    
    # Generate header content
    lines = []
    lines.append('#pragma once')
    lines.append('')
    lines.append('// Auto-generated file - DO NOT EDIT')
    lines.append('// Generated by compile_shaders.py from core/shaders/')
    lines.append('// Contains shader sources for all supported graphics backends')
    lines.append('// Large shaders are split into chunks to avoid C++ string literal size limits')
    lines.append('')
    lines.append('#include <string>')
    lines.append('')
    lines.append('namespace lupine {')
    lines.append('namespace GeneratedShaders {')
    lines.append('')
    
    total_shaders = 0
    
    # Process each backend
    for backend in backends:
        backend_dir = shader_base_dir / backend
        
        if not backend_dir.exists():
            continue
        
        lines.append(f'// ===== {backend} Shaders =====')
        lines.append(f'namespace {backend} {{')
        lines.append('')
        
        # Find all shader files in this backend directory
        shader_files = []
        for ext in ['.vert', '.frag', '.glsl', '.hlsl', '.metal']:
            shader_files.extend(backend_dir.glob(f'*{ext}'))
        
        shader_files.sort()
        
        for shader_file in shader_files:
            # Read shader source
            with open(shader_file, 'r', encoding='utf-8') as f:
                source = f.read()
            
            # Generate variable name from filename (remove extension, convert to valid C++ identifier)
            var_name = shader_file.stem.replace('-', '_').replace('.', '_')
            extension = shader_file.suffix[1:]  # Remove the dot
            
            # Split into lines for chunking
            source_lines = source.split('\n')
            chunks = split_shader_into_chunks(source_lines)
            
            if len(chunks) == 1:
                # Single chunk - use simple raw string literal
                lines.append(f'constexpr const char* {var_name}_{extension} = R"(')
                lines.append(source)
                lines.append(')";')
                lines.append('')
            else:
                # Multiple chunks - need to concatenate at runtime
                lines.append(f'// Large shader split into {len(chunks)} chunks')
                
                # Generate chunk variables
                for i, chunk in enumerate(chunks):
                    chunk_source = '\n'.join(chunk)
                    lines.append(f'constexpr const char* {var_name}_{extension}_chunk{i} = R"(')
                    lines.append(chunk_source)
                    lines.append(')";')
                    lines.append('')
                
                # Generate concatenation function
                lines.append(f'inline std::string get_{var_name}_{extension}() {{')
                lines.append(f'    std::string result;')
                lines.append(f'    result.reserve({len(source) + 100});  // Pre-allocate')
                for i in range(len(chunks)):
                    lines.append(f'    result += {var_name}_{extension}_chunk{i};')
                lines.append(f'    return result;')
                lines.append(f'}}')
                lines.append('')
                
                # For compatibility, create a static string that gets initialized once
                lines.append(f'inline const char* {var_name}_{extension}() {{')
                lines.append(f'    static const std::string shader = get_{var_name}_{extension}();')
                lines.append(f'    return shader.c_str();')
                lines.append(f'}}')
                lines.append('')
            
            total_shaders += 1
        
        lines.append(f'}} // namespace {backend}')
        lines.append('')
    
    lines.append('} // namespace GeneratedShaders')
    lines.append('} // namespace lupine')
    lines.append('')
    
    # Write output file
    output_file.parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    
    print(f'Generated {output_file} with {total_shaders} shaders across {len(backends)} backends')
    return total_shaders

if __name__ == '__main__':
    script_dir = Path(__file__).parent
    shader_base_dir = script_dir
    output_file = script_dir.parent / 'include' / 'lupine' / 'rendering' / 'GeneratedShaders.hpp'
    
    count = generate_shader_header(shader_base_dir, output_file)
    sys.exit(0 if count > 0 else 1)
