#pragma once

// Auto-generated file - DO NOT EDIT
// Generated by compile_shaders.py from core/shaders/
// Contains shader sources for all supported graphics backends
// Large shaders are split into chunks to avoid C++ string literal size limits

#include <string>

namespace lupine {
namespace GeneratedShaders {

// ===== OpenGL Shaders =====
namespace OpenGL {

constexpr const char* line_frag = R"(

#version 330 core

in vec4 v_Color;

uniform vec4 u_TintColor;

out vec4 FragColor;

void main() {
    FragColor = v_Color * u_TintColor;
}

)";

constexpr const char* line_vert = R"(

#version 330 core

layout(location = 0) in vec3 a_Position;
layout(location = 1) in vec3 a_Normal;
layout(location = 2) in vec2 a_TexCoord;
layout(location = 3) in vec4 a_Color;

uniform mat4 u_ViewProjection;

out vec4 v_Color;

void main() {
    v_Color = a_Color;
    gl_Position = u_ViewProjection * vec4(a_Position, 1.0);
}

)";

// Large shader split into 3 chunks
constexpr const char* p_b_r_frag_chunk0 = R"(

#version 330 core

// Vertex inputs
in vec3 v_WorldPos;
in vec3 v_ViewPos;
in vec3 v_Normal;
in vec2 v_TexCoord;
in vec4 v_Color;
in vec3 v_ViewDir;

// Material textures
uniform sampler2D u_AlbedoTexture;
uniform sampler2D u_MetallicRoughnessTexture;
uniform sampler2D u_NormalTexture;
uniform sampler2D u_EmissiveTexture;
uniform sampler2D u_AOTexture;

// Shadow map textures (up to 32 shadow maps for cascades)
uniform sampler2D u_ShadowMap0;
uniform sampler2D u_ShadowMap1;
uniform sampler2D u_ShadowMap2;
uniform sampler2D u_ShadowMap3;
uniform sampler2D u_ShadowMap4;
uniform sampler2D u_ShadowMap5;
uniform sampler2D u_ShadowMap6;
uniform sampler2D u_ShadowMap7;
uniform sampler2D u_ShadowMap8;
uniform sampler2D u_ShadowMap9;
uniform sampler2D u_ShadowMap10;
uniform sampler2D u_ShadowMap11;
uniform sampler2D u_ShadowMap12;
uniform sampler2D u_ShadowMap13;
uniform sampler2D u_ShadowMap14;
uniform sampler2D u_ShadowMap15;
uniform sampler2D u_ShadowMap16;
uniform sampler2D u_ShadowMap17;
uniform sampler2D u_ShadowMap18;
uniform sampler2D u_ShadowMap19;
uniform sampler2D u_ShadowMap20;
uniform sampler2D u_ShadowMap21;
uniform sampler2D u_ShadowMap22;
uniform sampler2D u_ShadowMap23;
uniform sampler2D u_ShadowMap24;
uniform sampler2D u_ShadowMap25;
uniform sampler2D u_ShadowMap26;
uniform sampler2D u_ShadowMap27;
uniform sampler2D u_ShadowMap28;
uniform sampler2D u_ShadowMap29;
uniform sampler2D u_ShadowMap30;
uniform sampler2D u_ShadowMap31;

// Cube map shadow textures for point lights (up to 8)
uniform samplerCube u_ShadowCubeMap0;
uniform samplerCube u_ShadowCubeMap1;
uniform samplerCube u_ShadowCubeMap2;
uniform samplerCube u_ShadowCubeMap3;
uniform samplerCube u_ShadowCubeMap4;
uniform samplerCube u_ShadowCubeMap5;
uniform samplerCube u_ShadowCubeMap6;
uniform samplerCube u_ShadowCubeMap7;

// Material properties
uniform vec4 u_AlbedoColor;
uniform vec4 u_EmissiveColor;
uniform vec4 u_MaterialParams1; // metallic, roughness, normalScale, emissiveStrength
uniform vec4 u_MaterialParams2; // alphaCutoff, aoStrength, heightScale, unused
uniform vec4 u_TextureFlags;    // useAlbedo, useMetallicRoughness, useNormal, useEmissive
uniform vec4 u_TintColor;

// Light data structure (matches GPULightData in Light.hpp)
struct Light {
    vec4 positionOrDirection; // w=0 for directional, w=1 for point/spot
    vec4 direction;           // xyz=direction for spot/directional lights, w=unused
    vec4 color;               // RGB + intensity in w
    vec4 params;              // x=range, y=innerConeAngle, z=outerConeAngle, w=attenuation
    vec4 flags;               // x=type, y=castShadows, z=shadowMapIndex, w=unused
};

// Shadow map data structure
struct ShadowMap {
    mat4 lightSpaceMatrix;   // Light space transformation matrix
    vec4 shadowParams;       // x=bias, y=normalBias, z=shadowBlur, w=shadowOpacity
    vec4 shadowParams2;      // x=shadowResolution, y=isCubeMap, z=lightRange (for cube maps), w=unused
};

// Cascaded shadow map data structure
struct CascadedShadowMap {
    mat4 cascadeMatrices[8]; // Light space matrix for each cascade
    vec4 cascadeSplits;      // Split distances for cascades 0-3 (x, y, z, w)
    vec4 cascadeSplits2;     // Split distances for cascades 4-7 (x, y, z, w)
    vec4 cascadeParams;      // x=cascadeCount, y=bias, z=normalBias, w=baseShadowMapIndex
};

// Light uniform buffer (std140 layout, binding point 0)
layout(std140) uniform LightData {
    Light lights[16];
    ShadowMap shadowMaps[8];  // Increased from 4 to 8 to match MAX_SHADOW_MAPS
    CascadedShadowMap cascadedShadowMaps[8];  // Increased from 4 to 8 to match MAX_SHADOW_MAPS
    vec4 ambientLight;       // RGB + intensity
    vec4 lightCounts;        // x=numLights, y=numShadowMaps, z=numCascadedShadowMaps, w=unused
} u_Lights;

out vec4 FragColor;

const float PI = 3.14159265359;

// Helper function to sample shadow map by index
float sampleShadowMap(int index, vec2 uv) {
    if (index == 0) return texture(u_ShadowMap0, uv).r;
    else if (index == 1) return texture(u_ShadowMap1, uv).r;
    else if (index == 2) return texture(u_ShadowMap2, uv).r;
    else if (index == 3) return texture(u_ShadowMap3, uv).r;
    else if (index == 4) return texture(u_ShadowMap4, uv).r;
    else if (index == 5) return texture(u_ShadowMap5, uv).r;
    else if (index == 6) return texture(u_ShadowMap6, uv).r;
    else if (index == 7) return texture(u_ShadowMap7, uv).r;
    else if (index == 8) return texture(u_ShadowMap8, uv).r;
    else if (index == 9) return texture(u_ShadowMap9, uv).r;
    else if (index == 10) return texture(u_ShadowMap10, uv).r;
    else if (index == 11) return texture(u_ShadowMap11, uv).r;
    else if (index == 12) return texture(u_ShadowMap12, uv).r;
    else if (index == 13) return texture(u_ShadowMap13, uv).r;
    else if (index == 14) return texture(u_ShadowMap14, uv).r;
    else if (index == 15) return texture(u_ShadowMap15, uv).r;
    else if (index == 16) return texture(u_ShadowMap16, uv).r;
    else if (index == 17) return texture(u_ShadowMap17, uv).r;
    else if (index == 18) return texture(u_ShadowMap18, uv).r;
    else if (index == 19) return texture(u_ShadowMap19, uv).r;
    else if (index == 20) return texture(u_ShadowMap20, uv).r;
    else if (index == 21) return texture(u_ShadowMap21, uv).r;
    else if (index == 22) return texture(u_ShadowMap22, uv).r;
    else if (index == 23) return texture(u_ShadowMap23, uv).r;
    else if (index == 24) return texture(u_ShadowMap24, uv).r;
    else if (index == 25) return texture(u_ShadowMap25, uv).r;
    else if (index == 26) return texture(u_ShadowMap26, uv).r;
    else if (index == 27) return texture(u_ShadowMap27, uv).r;
    else if (index == 28) return texture(u_ShadowMap28, uv).r;
    else if (index == 29) return texture(u_ShadowMap29, uv).r;
    else if (index == 30) return texture(u_ShadowMap30, uv).r;
    else if (index == 31) return texture(u_ShadowMap31, uv).r;
    return 1.0;
}

// Helper function to sample cube shadow map by index
float sampleShadowCubeMap(int index, vec3 dir) {
    // For GL_DEPTH_COMPONENT textures, texture() returns a vec4 where all components contain the depth
    // We can use .r, .x, or just the scalar value
    vec4 sample;
    if (index == 0) sample = texture(u_ShadowCubeMap0, dir);
    else if (index == 1) sample = texture(u_ShadowCubeMap1, dir);
    else if (index == 2) sample = texture(u_ShadowCubeMap2, dir);
    else if (index == 3) sample = texture(u_ShadowCubeMap3, dir);
    else if (index == 4) sample = texture(u_ShadowCubeMap4, dir);
    else if (index == 5) sample = texture(u_ShadowCubeMap5, dir);
    else if (index == 6) sample = texture(u_ShadowCubeMap6, dir);
    else if (index == 7) sample = texture(u_ShadowCubeMap7, dir);
    else return 1.0;

    // Return the red channel which contains the depth value
    return sample.r;
}

// DEBUG: Global variables for visualization
int g_debugCascadeIndex = -1;
int g_debugShadowMapIndex = -1;
float g_debugShadowValue = -1.0;
vec3 g_debugProjCoords = vec3(-1.0);
float g_debugSampledDepth = -1.0;

// Calculate shadow factor for a single shadow map with PCF
float calculateShadowPCF(mat4 lightSpaceMatrix, int shadowMapIndex, vec3 worldPos, vec3 normal, vec3 lightDir, float bias, float normalBias, float shadowBlur, float shadowOpacity, float shadowResolution) {
    // Transform world position to light space (no normal bias initially for debugging)
    vec4 lightSpacePos = lightSpaceMatrix * vec4(worldPos, 1.0);

    // Perform perspective divide
    vec3 projCoords = lightSpacePos.xyz / lightSpacePos.w;

    // Transform to [0,1] range
    projCoords = projCoords * 0.5 + 0.5;

    // NOTE: Y-flip removed - framebuffer depth textures in OpenGL have matching coordinate systems
    // The Y-flip was causing inverted shadows (shadows pointing toward light instead of away)
    // projCoords.y = 1.0 - projCoords.y;

    // DEBUG: Store projected coordinates
    g_debugProjCoords = projCoords;

    // Check if outside shadow map bounds
    if (projCoords.z > 1.0 || projCoords.x < 0.0 || projCoords.x > 1.0 ||
        projCoords.y < 0.0 || projCoords.y > 1.0) {
        g_debugSampledDepth = -2.0; // Mark as out of bounds
        return 1.0; // Outside shadow map, no shadow
    }

    float currentDepth = projCoords.z;

    // DEBUG: Sample shadow map and store for visualization
    float sampledDepth = sampleShadowMap(shadowMapIndex, projCoords.xy);
    g_debugSampledDepth = sampledDepth;
)";

constexpr const char* p_b_r_frag_chunk1 = R"(

    // Calculate bias based on surface angle to light to prevent shadow acne
    float NdotL = max(dot(normal, lightDir), 0.0);
    // Angle-based bias: surfaces perpendicular to light need less bias
    // Use smaller bias multipliers to prevent over-biasing
    float minBias = bias;
    float maxBias = bias * 2.0;
    float finalBias = mix(maxBias, minBias, NdotL);

    // PCF (Percentage Closer Filtering) for soft shadows
    // shadowBlur controls the PCF kernel size (1.0 = 3x3, higher = larger kernel)
    float shadow = 0.0;
    vec2 texelSize = 1.0 / vec2(shadowResolution, shadowResolution); // Dynamic shadow map resolution
    
    // Scale PCF kernel based on blur amount
    int kernelRadius = int(shadowBlur);
    kernelRadius = clamp(kernelRadius, 1, 3); // Limit to 1-3 for performance
    int sampleCount = 0;

    for(int x = -kernelRadius; x <= kernelRadius; ++x) {
        for(int y = -kernelRadius; y <= kernelRadius; ++y) {
            vec2 offset = vec2(x, y) * texelSize * shadowBlur;
            float pcfDepth = sampleShadowMap(shadowMapIndex, projCoords.xy + offset);

            // DEBUG: Store first sample depth
            if (x == 0 && y == 0) {
                g_debugSampledDepth = pcfDepth;
            }

            shadow += currentDepth - finalBias > pcfDepth ? 1.0 : 0.0;
            sampleCount++;
        }
    }
    shadow /= float(sampleCount);

    // Apply shadow opacity (1.0 = full shadow, 0.0 = no shadow)
    shadow *= shadowOpacity;

    return 1.0 - shadow;
}

// Calculate shadow factor for cube map (point lights)
float calculateShadowCube(int cubeMapIndex, vec3 lightPos, vec3 worldPos, vec3 normal, float bias, float shadowBlur, float shadowOpacity, float lightRange) {
    // Calculate direction from light to fragment
    vec3 fragToLight = worldPos - lightPos;
    float currentDepth = length(fragToLight);

    // Normalize current depth to [0,1] range
    float normalizedCurrentDepth = currentDepth / lightRange;

    // Normalize direction for sampling
    vec3 sampleDir = normalize(fragToLight);

    // Sample the cube map (already stores normalized linear depth in [0,1])
    float closestDepth = sampleShadowCubeMap(cubeMapIndex, sampleDir);

    // Calculate bias based on surface angle to light
    vec3 lightDir = -sampleDir;
    float NdotL = max(dot(normal, lightDir), 0.0);
    // Bias needs to be in normalized [0,1] space to match the depth values
    float normalizedBias = bias / lightRange;
    float minBias = normalizedBias * 0.5;
    float maxBias = normalizedBias * 3.0;
    float finalBias = mix(maxBias, minBias, NdotL);

    // Simple PCF for cube maps
    float shadow = 0.0;
    if (shadowBlur > 1.0) {
        // Sample neighboring texels for soft shadows
        vec3 sampleOffsetDirections[20] = vec3[]
        (
           vec3( 1,  1,  1), vec3( 1, -1,  1), vec3(-1, -1,  1), vec3(-1,  1,  1),
           vec3( 1,  1, -1), vec3( 1, -1, -1), vec3(-1, -1, -1), vec3(-1,  1, -1),
           vec3( 1,  1,  0), vec3( 1, -1,  0), vec3(-1, -1,  0), vec3(-1,  1,  0),
           vec3( 1,  0,  1), vec3(-1,  0,  1), vec3( 1,  0, -1), vec3(-1,  0, -1),
           vec3( 0,  1,  1), vec3( 0, -1,  1), vec3( 0, -1, -1), vec3( 0,  1, -1)
        );

        float diskRadius = 0.05 * shadowBlur;
        int samples = 20;
        for(int i = 0; i < samples; ++i) {
            vec3 offsetDir = sampleDir + sampleOffsetDirections[i] * diskRadius;
            float sampledDepth = sampleShadowCubeMap(cubeMapIndex, offsetDir);
            shadow += (normalizedCurrentDepth - finalBias) > sampledDepth ? 1.0 : 0.0;
        }
        shadow /= float(samples);
    } else {
        // No PCF, single sample
        shadow = (normalizedCurrentDepth - finalBias) > closestDepth ? 1.0 : 0.0;
    }

    // Apply shadow opacity
    shadow *= shadowOpacity;

    return 1.0 - shadow;
}

// Calculate shadow factor for cascaded shadow maps (directional lights)
float calculateCascadedShadow(int csmIndex, vec3 worldPos, vec3 viewPos, vec3 normal, vec3 lightDir) {
    if (csmIndex < 0 || csmIndex >= 4) {
        return 1.0; // No shadow
    }

    CascadedShadowMap csm = u_Lights.cascadedShadowMaps[csmIndex];
    int cascadeCount = int(csm.cascadeParams.x);
    float bias = csm.cascadeParams.y;
    float normalBias = csm.cascadeParams.z;
    int baseShadowMapIndex = int(csm.cascadeParams.w);

    // Calculate view-space depth
    float viewDepth = abs(viewPos.z);

    // Select cascade based on view depth
    int cascadeIndex = cascadeCount - 1;
    for (int i = 0; i < cascadeCount - 1; ++i) {
        float splitDistance = 0.0;
        if (i < 4) {
            splitDistance = csm.cascadeSplits[i];
        } else {
            splitDistance = csm.cascadeSplits2[i - 4];
        }

        if (viewDepth < splitDistance) {
            cascadeIndex = i;
            break;
        }
    }

    // DEBUG: Store cascade index for visualization
    g_debugCascadeIndex = cascadeIndex;

    // Calculate shadow map index (base index + cascade offset)
    int shadowMapIndex = baseShadowMapIndex + cascadeIndex;
    g_debugShadowMapIndex = shadowMapIndex;

    // Calculate shadow using selected cascade
    mat4 lightSpaceMatrix = csm.cascadeMatrices[cascadeIndex];
    // For cascaded shadows, use default values for blur/opacity/resolution (TODO: pass from CPU)
    float shadow = calculateShadowPCF(lightSpaceMatrix, shadowMapIndex, worldPos, normal, lightDir, bias, normalBias, 1.0, 1.0, 2048.0);
    g_debugShadowValue = shadow;
    return shadow;
}

// Calculate shadow factor for a given shadow map (non-cascaded)
float calculateShadow(int shadowMapIndex, vec3 worldPos, vec3 normal, vec3 lightDir, vec3 lightPos) {
    if (shadowMapIndex < 0 || shadowMapIndex >= 8) {
        return 1.0; // No shadow
    }

    ShadowMap shadowMap = u_Lights.shadowMaps[shadowMapIndex];

    // Check if this is a cube map shadow (for point lights)
    bool isCubeMap = shadowMap.shadowParams2.y > 0.5;

    if (isCubeMap) {
        // Use cube map shadow calculation for point lights
        float lightRange = shadowMap.shadowParams2.z;
        return calculateShadowCube(shadowMapIndex, lightPos, worldPos, normal,
                                  shadowMap.shadowParams.x, shadowMap.shadowParams.z,
                                  shadowMap.shadowParams.w, lightRange);
    } else {
        // Use standard 2D shadow map calculation
        return calculateShadowPCF(shadowMap.lightSpaceMatrix, shadowMapIndex, worldPos, normal, lightDir,
                                  shadowMap.shadowParams.x, shadowMap.shadowParams.y,
                                  shadowMap.shadowParams.z, shadowMap.shadowParams.w,
                                  shadowMap.shadowParams2.x);
    }
}

// Normal mapping
vec3 getNormalFromMap() {
    if (u_TextureFlags.z < 0.5) {
        return normalize(v_Normal);
    }

    vec3 tangentNormal = texture(u_NormalTexture, v_TexCoord).xyz * 2.0 - 1.0;
    tangentNormal.xy *= u_MaterialParams1.z; // normalScale

    // Construct TBN matrix
    vec3 Q1 = dFdx(v_WorldPos);
    vec3 Q2 = dFdy(v_WorldPos);
    vec2 st1 = dFdx(v_TexCoord);
    vec2 st2 = dFdy(v_TexCoord);

    vec3 N = normalize(v_Normal);
    vec3 T = normalize(Q1 * st2.t - Q2 * st1.t);
    vec3 B = -normalize(cross(N, T));
    mat3 TBN = mat3(T, B, N);

    return normalize(TBN * tangentNormal);
}

// Fresnel-Schlick approximation
vec3 fresnelSchlick(float cosTheta, vec3 F0) {
    return F0 + (1.0 - F0) * pow(clamp(1.0 - cosTheta, 0.0, 1.0), 5.0);
}

// GGX/Trowbridge-Reitz normal distribution
float distributionGGX(vec3 N, vec3 H, float roughness) {
    float a = roughness * roughness;
)";

constexpr const char* p_b_r_frag_chunk2 = R"(
    float a2 = a * a;
    float NdotH = max(dot(N, H), 0.0);
    float NdotH2 = NdotH * NdotH;

    float num = a2;
    float denom = (NdotH2 * (a2 - 1.0) + 1.0);
    denom = PI * denom * denom;

    return num / denom;
}

// Smith's Schlick-GGX geometry function
float geometrySchlickGGX(float NdotV, float roughness) {
    float r = (roughness + 1.0);
    float k = (r * r) / 8.0;

    float num = NdotV;
    float denom = NdotV * (1.0 - k) + k;

    return num / denom;
}

float geometrySmith(vec3 N, vec3 V, vec3 L, float roughness) {
    float NdotV = max(dot(N, V), 0.0);
    float NdotL = max(dot(N, L), 0.0);
    float ggx2 = geometrySchlickGGX(NdotV, roughness);
    float ggx1 = geometrySchlickGGX(NdotL, roughness);

    return ggx1 * ggx2;
}

void main() {
    // Sample material properties
    vec4 albedo = u_AlbedoColor;
    if (u_TextureFlags.x > 0.5) {
        albedo *= texture(u_AlbedoTexture, v_TexCoord);
    }

    // Alpha test
    if (albedo.a < u_MaterialParams2.x) {
        discard;
    }

    float metallic = u_MaterialParams1.x;
    float roughness = u_MaterialParams1.y;
    if (u_TextureFlags.y > 0.5) {
        vec3 mrSample = texture(u_MetallicRoughnessTexture, v_TexCoord).rgb;
        roughness *= mrSample.g;
        metallic *= mrSample.b;
    }

    vec3 emissive = u_EmissiveColor.rgb * u_MaterialParams1.w;
    if (u_TextureFlags.w > 0.5) {
        emissive *= texture(u_EmissiveTexture, v_TexCoord).rgb;
    }

    float ao = 1.0;
    // AO texture support can be added here

    // Get normal
    vec3 N = getNormalFromMap();
    vec3 V = normalize(v_ViewDir);

    // Calculate reflectance at normal incidence
    vec3 F0 = vec3(0.04);
    F0 = mix(F0, albedo.rgb, metallic);

    // Accumulate lighting from all lights
    vec3 Lo = vec3(0.0);
    int numLights = int(u_Lights.lightCounts.x);

    for (int i = 0; i < numLights && i < 16; ++i) {
        Light light = u_Lights.lights[i];
        int lightType = int(light.flags.x);
        bool castsShadows = light.flags.y > 0.5;
        int shadowMapIndex = int(light.flags.z);

        vec3 L;
        float attenuation = 1.0;

        // Calculate light direction and attenuation based on type
        if (lightType == 0) {
            // Directional light
            L = normalize(-light.direction.xyz);
        } else if (lightType == 1) {
            // Point light
            vec3 lightPos = light.positionOrDirection.xyz;
            vec3 lightDir = lightPos - v_WorldPos;
            float distance = length(lightDir);
            L = normalize(lightDir);

            float range = light.params.x;
            float attenuationExp = light.params.w;

            // Distance-based attenuation with configurable exponent
            // Using inverse square law as base, modified by attenuation exponent
            float distanceFactor = distance / range;
            attenuation = 1.0 / (1.0 + pow(distanceFactor, attenuationExp));

            // Smooth cutoff at range boundary
            attenuation *= smoothstep(1.0, 0.5, distanceFactor);
        } else if (lightType == 2) {
            // Spot light
            vec3 lightPos = light.positionOrDirection.xyz;
            vec3 lightDir = lightPos - v_WorldPos;
            float distance = length(lightDir);
            L = normalize(lightDir);

            vec3 spotDir = normalize(light.direction.xyz);
            float theta = dot(L, -spotDir);
            float innerCutoff = light.params.y; // Already cosine
            float outerCutoff = light.params.z; // Already cosine

            // Calculate spot intensity with smooth falloff
            // Use max to prevent division by zero when inner and outer cutoffs are too close
            float epsilon = max(innerCutoff - outerCutoff, 0.0001);
            float spotIntensity = clamp((theta - outerCutoff) / epsilon, 0.0, 1.0);
            // Apply smooth curve for better visual falloff
            spotIntensity = smoothstep(0.0, 1.0, spotIntensity);

            float range = light.params.x;
            float attenuationExp = light.params.w;

            // Distance-based attenuation with configurable exponent
            float distanceFactor = clamp(distance / range, 0.0, 1.0);
            attenuation = 1.0 / (1.0 + pow(distanceFactor, attenuationExp));

            // Smooth cutoff at range boundary
            attenuation *= smoothstep(1.0, 0.5, distanceFactor);

            // Apply spot intensity to attenuation
            attenuation *= spotIntensity;
        }

        vec3 H = normalize(V + L);

        // Cook-Torrance BRDF
        float NDF = distributionGGX(N, H, roughness);
        float G = geometrySmith(N, V, L, roughness);
        vec3 F = fresnelSchlick(max(dot(H, V), 0.0), F0);

        vec3 kS = F;
        vec3 kD = vec3(1.0) - kS;
        kD *= 1.0 - metallic;

        vec3 numerator = NDF * G * F;
        float denominator = 4.0 * max(dot(N, V), 0.0) * max(dot(N, L), 0.0) + 0.0001;
        vec3 specular = numerator / denominator;

        float NdotL = max(dot(N, L), 0.0);

        // Calculate shadow
        float shadow = 1.0;
        if (castsShadows && shadowMapIndex >= 0) {
            // All lights with shadows use the standard shadow map path
            // (spot, omni, and directional lights all use non-cascaded shadows for now)
            vec3 lightPos = light.positionOrDirection.xyz;
            shadow = calculateShadow(shadowMapIndex, v_WorldPos, N, L, lightPos);
        }

        vec3 radiance = light.color.rgb * light.color.w * attenuation;
        Lo += (kD * albedo.rgb / PI + specular) * radiance * NdotL * shadow;
    }

    // Ambient lighting
    vec3 ambient = u_Lights.ambientLight.rgb * u_Lights.ambientLight.a * albedo.rgb * ao;

    // Apply tint color
    vec3 color = (ambient + Lo + emissive) * u_TintColor.rgb;

    // HDR tonemapping (simple Reinhard)
    color = color / (color + vec3(1.0));

    // Gamma correction
    color = pow(color, vec3(1.0/2.2));

    FragColor = vec4(color, albedo.a);
}

)";

inline std::string get_p_b_r_frag() {
    std::string result;
    result.reserve(22252);  // Pre-allocate
    result += p_b_r_frag_chunk0;
    result += p_b_r_frag_chunk1;
    result += p_b_r_frag_chunk2;
    return result;
}

inline const char* p_b_r_frag() {
    static const std::string shader = get_p_b_r_frag();
    return shader.c_str();
}

constexpr const char* p_b_r_vert = R"(

#version 330 core

layout(location = 0) in vec3 a_Position;
layout(location = 1) in vec3 a_Normal;
layout(location = 2) in vec2 a_TexCoord;
layout(location = 3) in vec4 a_Color;

uniform mat4 u_ViewProjection;
uniform mat4 u_View;
uniform mat4 u_Model;
uniform mat4 u_NormalMatrix;
uniform vec3 u_CameraPosition;

out vec3 v_WorldPos;
out vec3 v_ViewPos;
out vec3 v_Normal;
out vec2 v_TexCoord;
out vec4 v_Color;
out vec3 v_ViewDir;

void main() {
    vec4 worldPos = u_Model * vec4(a_Position, 1.0);
    v_WorldPos = worldPos.xyz;
    v_ViewPos = (u_View * worldPos).xyz;
    v_Normal = mat3(u_NormalMatrix) * a_Normal;
    v_TexCoord = a_TexCoord;
    v_Color = a_Color;
    v_ViewDir = normalize(u_CameraPosition - v_WorldPos);

    gl_Position = u_ViewProjection * worldPos;
}

)";

constexpr const char* pbr_vert = R"(
#version 330 core

layout(location = 0) in vec3 a_Position;
layout(location = 1) in vec3 a_Normal;
layout(location = 2) in vec2 a_TexCoord;
layout(location = 3) in vec4 a_Color;

uniform mat4 u_ViewProjection;
uniform mat4 u_Model;
uniform mat4 u_NormalMatrix;
uniform mat4 u_View;
uniform vec3 u_CameraPosition;

out vec3 v_WorldPos;
out vec3 v_ViewPos;
out vec3 v_Normal;
out vec2 v_TexCoord;
out vec4 v_Color;
out vec3 v_ViewDir;

void main() {
    vec4 worldPos = u_Model * vec4(a_Position, 1.0);
    v_WorldPos = worldPos.xyz;
    v_ViewPos = (u_View * worldPos).xyz;
    v_Normal = mat3(u_NormalMatrix) * a_Normal;
    v_TexCoord = a_TexCoord;
    v_Color = a_Color;
    v_ViewDir = normalize(u_CameraPosition - v_WorldPos);

    gl_Position = u_ViewProjection * worldPos;
}

)";

constexpr const char* rounded_rect_frag = R"(

#version 330 core

in vec2 v_TexCoord;
in vec4 v_Color;
in vec2 v_LocalPos;

uniform sampler2D u_Texture;
uniform vec4 u_TintColor;
uniform vec4 u_Color;          // Direct color (used by 3D components)
uniform bool u_UseTexture;
uniform vec4 u_CornerRadius;  // x=top-left, y=top-right, z=bottom-right, w=bottom-left
uniform vec2 u_Size;           // Width and height of the rectangle
uniform vec2 u_UVMin;          // Minimum UV coordinates (default 0,0)
uniform vec2 u_UVMax;          // Maximum UV coordinates (default 1,1)

out vec4 FragColor;

// Signed distance function for a rounded rectangle
float sdRoundedBox(vec2 p, vec2 size, vec4 radius) {
    // Convert position from center-based (-0.5 to 0.5) to size-based coordinates
    vec2 pos = p * size;
    vec2 halfSize = size * 0.5;
    
    // Select the appropriate corner radius based on quadrant
    float r;
    if (pos.x > 0.0) {
        r = (pos.y > 0.0) ? radius.z : radius.y;  // bottom-right : top-right
    } else {
        r = (pos.y > 0.0) ? radius.w : radius.x;  // bottom-left : top-left
    }
    
    // Clamp radius to not exceed half the minimum dimension
    r = min(r, min(halfSize.x, halfSize.y));
    
    // Calculate distance to rounded corner
    vec2 q = abs(pos) - halfSize + r;
    float dist = length(max(q, 0.0)) + min(max(q.x, q.y), 0.0) - r;
    
    return dist;
}

void main() {
    // Calculate distance to edge
    float dist = sdRoundedBox(v_LocalPos, u_Size, u_CornerRadius);

    // Smooth antialiasing at edges (1 pixel transition)
    float edgeSoftness = 1.5 / length(u_Size);  // Adjust based on size
    float alpha = 1.0 - smoothstep(-edgeSoftness, edgeSoftness, dist);

    // Base color - use u_Color if set (alpha > 0), otherwise fall back to v_Color * u_TintColor
    // This allows 3D components to use u_Color directly while maintaining compatibility with 2D components
    vec4 color;
    if (u_Color.a > 0.0) {
        color = u_Color;
    } else {
        color = v_Color * u_TintColor;
    }

    // Apply texture if enabled
    if (u_UseTexture) {
        // Remap texture coordinates from 0-1 to uvMin-uvMax range
        vec2 remappedUV = u_UVMin + (v_TexCoord * (u_UVMax - u_UVMin));
        color *= texture(u_Texture, remappedUV);
    }

    // Apply corner rounding alpha
    color.a *= alpha;

    // Discard fully transparent pixels for performance
    if (color.a < 0.01) {
        discard;
    }

    FragColor = color;
}

)";

constexpr const char* rounded_rect_vert = R"(

#version 330 core

layout(location = 0) in vec3 a_Position;
layout(location = 1) in vec2 a_TexCoord;
layout(location = 2) in vec4 a_Color;

uniform mat4 u_ViewProjection;
uniform mat4 u_Model;

out vec2 v_TexCoord;
out vec4 v_Color;
out vec2 v_LocalPos;  // Position in quad space (-0.5 to 0.5)

void main() {
    v_TexCoord = a_TexCoord;
    v_Color = a_Color;
    v_LocalPos = a_Position.xy;  // Store local position for distance calculations
    gl_Position = u_ViewProjection * u_Model * vec4(a_Position, 1.0);
}

)";

constexpr const char* rounded_rect_border_frag = R"(

#version 330 core

in vec2 v_TexCoord;
in vec4 v_Color;
in vec2 v_LocalPos;

uniform vec4 u_TintColor;
uniform vec4 u_Color;             // Direct color (used by 3D components)
uniform vec4 u_CornerRadius;     // Outer corner radius (x=top-left, y=top-right, z=bottom-right, w=bottom-left)
uniform vec2 u_Size;              // Outer size of the border rectangle
uniform vec4 u_BorderWidth;       // Border widths (x=top, y=right, z=bottom, w=left)
uniform bool u_EnableAntialiasing; // Enable/disable edge antialiasing (default: true)

out vec4 FragColor;

// Signed distance function for a rounded rectangle
// p: position relative to center (in pixel space)
// size: full size of rectangle
// radius: corner radii (top-left, top-right, bottom-right, bottom-left)
float sdRoundedBox(vec2 p, vec2 size, vec4 radius) {
    vec2 halfSize = size * 0.5;
    
    // Select the appropriate corner radius based on quadrant
    float r;
    if (p.x > 0.0) {
        r = (p.y > 0.0) ? radius.z : radius.y;  // bottom-right : top-right
    } else {
        r = (p.y > 0.0) ? radius.w : radius.x;  // bottom-left : top-left
    }
    
    // Clamp radius to not exceed half the minimum dimension
    r = min(r, min(halfSize.x, halfSize.y));
    
    // Calculate distance to rounded corner
    vec2 q = abs(p) - halfSize + r;
    float dist = length(max(q, 0.0)) + min(max(q.x, q.y), 0.0) - r;
    
    return dist;
}

void main() {
    // Convert normalized position (-0.5 to 0.5) to pixel space (centered at origin)
    vec2 pixelPos = v_LocalPos * u_Size;
    
    // Calculate distance to outer edge
    float outerDist = sdRoundedBox(pixelPos, u_Size, u_CornerRadius);

    // Antialiasing control
    float edgeSoftness = u_EnableAntialiasing ? 1.5 : 0.0;
    float outerAlpha = 1.0 - smoothstep(-edgeSoftness, edgeSoftness, outerDist);
    
    // Calculate inner size (subtract border widths from outer size)
    // borderWidth: x=top, y=right, z=bottom, w=left
    vec2 innerSize = u_Size - vec2(u_BorderWidth.w + u_BorderWidth.y, u_BorderWidth.x + u_BorderWidth.z);
    
    float innerAlpha = 1.0;  // Default: show border (no cutout)
    
    // Only calculate inner cutout if inner size is valid
    if (innerSize.x > 0.0 && innerSize.y > 0.0) {
        // Calculate inner corner radius
        // Each corner's inner radius = outer radius - adjacent border widths
        // For corners, we subtract the smaller of the two adjacent borders to maintain continuity
        vec4 innerRadius = vec4(
            max(0.0, u_CornerRadius.x - min(u_BorderWidth.x, u_BorderWidth.w)),  // top-left
            max(0.0, u_CornerRadius.y - min(u_BorderWidth.x, u_BorderWidth.y)),  // top-right
            max(0.0, u_CornerRadius.z - min(u_BorderWidth.z, u_BorderWidth.y)),  // bottom-right
            max(0.0, u_CornerRadius.w - min(u_BorderWidth.z, u_BorderWidth.w))   // bottom-left
        );
        
        // Offset position for inner rectangle (account for non-uniform borders)
        // The inner rect is offset by half the difference between opposite borders
        vec2 borderOffset = vec2(
            (u_BorderWidth.w - u_BorderWidth.y) * 0.5,  // x offset: (left - right) / 2
            (u_BorderWidth.x - u_BorderWidth.z) * 0.5   // y offset: (top - bottom) / 2
        );
        
        vec2 innerPos = pixelPos - borderOffset;
        float innerDist = sdRoundedBox(innerPos, innerSize, innerRadius);
        
        // If inside inner rect (negative distance), hide this pixel to create the border
        // smoothstep returns 0 when innerDist < -edgeSoftness (inside - should be transparent)
        // smoothstep returns 1 when innerDist > edgeSoftness (outside - should be opaque)
        innerAlpha = smoothstep(-edgeSoftness, edgeSoftness, innerDist);
    }
    
    // Final alpha: show where outer shape is AND where inner cutout isn't
    float alpha = outerAlpha * innerAlpha;

    // Apply color - use u_Color if set (alpha > 0), otherwise fall back to v_Color * u_TintColor
    // This allows 3D components to use u_Color directly while maintaining compatibility with 2D components
    vec4 color;
    if (u_Color.a > 0.0) {
        color = u_Color;
    } else {
        color = v_Color * u_TintColor;
    }
    color.a *= alpha;

    // Discard fully transparent pixels
    if (color.a < 0.01) {
        discard;
    }

    FragColor = color;
}

)";

constexpr const char* rounded_rect_border_vert = R"(

#version 330 core

layout(location = 0) in vec3 a_Position;
layout(location = 1) in vec2 a_TexCoord;
layout(location = 2) in vec4 a_Color;

uniform mat4 u_ViewProjection;
uniform mat4 u_Model;

out vec2 v_TexCoord;
out vec4 v_Color;
out vec2 v_LocalPos;  // Position in quad space (-0.5 to 0.5)

void main() {
    v_TexCoord = a_TexCoord;
    v_Color = a_Color;
    v_LocalPos = a_Position.xy;  // Store local position for distance calculations
    gl_Position = u_ViewProjection * u_Model * vec4(a_Position, 1.0);
}

)";

constexpr const char* shadow_cube_frag = R"(

#version 330 core

in vec2 v_TexCoord;
in vec3 v_WorldPos;

// Output to color attachment (R32_FLOAT)
out float fragDepth;

// Material textures
uniform sampler2D u_AlbedoTexture;
uniform int u_HasAlbedoTexture;
uniform float u_AlphaCutoff;

// Light position and range for cube map shadows
uniform vec3 u_LightPos;
uniform float u_LightRange;

void main() {
    // Alpha testing for transparent materials (e.g., leaves, grass)
    if (u_HasAlbedoTexture == 1) {
        float alpha = texture(u_AlbedoTexture, v_TexCoord).a;
        if (alpha < u_AlphaCutoff) {
            discard; // Don't cast shadow for transparent pixels
        }
    }

    // Calculate linear depth (distance from light) and normalize to [0,1]
    float lightDistance = length(v_WorldPos - u_LightPos);
    float linearDepth = lightDistance / u_LightRange;

    // Clamp to [0,1] range to ensure valid depth values
    linearDepth = clamp(linearDepth, 0.0, 1.0);

    // Output the normalized linear depth to the color attachment
    // This will be sampled as-is in the PBR shader
    fragDepth = linearDepth;
}


)";

constexpr const char* shadow_cube_vert = R"(

#version 330 core

layout(location = 0) in vec3 a_Position;
layout(location = 1) in vec2 a_TexCoord;

out vec2 v_TexCoord;
out vec3 v_WorldPos;

uniform mat4 u_LightSpaceMatrix;
uniform mat4 u_Model;

void main() {
    v_TexCoord = a_TexCoord;
    v_WorldPos = (u_Model * vec4(a_Position, 1.0)).xyz;
    gl_Position = u_LightSpaceMatrix * u_Model * vec4(a_Position, 1.0);
}


)";

constexpr const char* shadow_map_frag = R"(

#version 330 core

in vec2 v_TexCoord;

// Material textures
uniform sampler2D u_AlbedoTexture;
uniform int u_HasAlbedoTexture;
uniform float u_AlphaCutoff;

void main() {
    // Alpha testing for transparent materials (e.g., leaves, grass)
    if (u_HasAlbedoTexture == 1) {
        float alpha = texture(u_AlbedoTexture, v_TexCoord).a;
        if (alpha < u_AlphaCutoff) {
            discard; // Don't cast shadow for transparent pixels
        }
    }

    // Depth is automatically written to the depth buffer
    // No color output needed for shadow maps
}

)";

constexpr const char* shadow_map_vert = R"(

#version 330 core

layout(location = 0) in vec3 a_Position;
layout(location = 1) in vec2 a_TexCoord;

out vec2 v_TexCoord;

uniform mat4 u_LightSpaceMatrix;
uniform mat4 u_Model;

void main() {
    v_TexCoord = a_TexCoord;
    gl_Position = u_LightSpaceMatrix * u_Model * vec4(a_Position, 1.0);
}

)";

constexpr const char* shadow_map_skeletal_vert = R"(

#version 330 core

layout(location = 0) in vec3 a_Position;
layout(location = 1) in vec3 a_Normal;
layout(location = 2) in vec2 a_TexCoord;
layout(location = 3) in vec4 a_Color;
layout(location = 4) in vec3 a_Tangent;
layout(location = 5) in vec4 a_BoneIDs;
layout(location = 6) in vec4 a_BoneWeights;

const int MAX_BONES = 128;
uniform mat4 u_BoneTransforms[MAX_BONES];
uniform bool u_UseSkinning;

out vec2 v_TexCoord;

uniform mat4 u_LightSpaceMatrix;
uniform mat4 u_Model;

void main() {
    vec4 localPos = vec4(a_Position, 1.0);
    
    // Apply skeletal animation if enabled
    if (u_UseSkinning) {
        mat4 boneTransform = mat4(0.0);
        float totalWeight = 0.0;
        
        // Accumulate bone transformations weighted by bone weights
        for (int i = 0; i < 4; i++) {
            int boneID = int(a_BoneIDs[i]);
            float weight = a_BoneWeights[i];
            
            if (boneID >= 0 && boneID < MAX_BONES && weight > 0.0) {
                boneTransform += u_BoneTransforms[boneID] * weight;
                totalWeight += weight;
            }
        }
        
        // Only apply bone transformation if we have valid weights
        if (totalWeight > 0.0) {
            localPos = boneTransform * localPos;
        }
    }
    
    v_TexCoord = a_TexCoord;
    gl_Position = u_LightSpaceMatrix * u_Model * localPos;
}



)";

// Large shader split into 3 chunks
constexpr const char* skeletal_frag_chunk0 = R"(

#version 330 core

in vec3 v_WorldPos;
in vec3 v_ViewPos;
in vec3 v_Normal;
in vec2 v_TexCoord;
in vec4 v_Color;
in vec3 v_ViewDir;

// Material textures
uniform sampler2D u_AlbedoTexture;
uniform sampler2D u_MetallicRoughnessTexture;
uniform sampler2D u_NormalTexture;
uniform sampler2D u_EmissiveTexture;

// Shadow map textures (up to 32 shadow maps for cascades)
uniform sampler2D u_ShadowMap0;
uniform sampler2D u_ShadowMap1;
uniform sampler2D u_ShadowMap2;
uniform sampler2D u_ShadowMap3;
uniform sampler2D u_ShadowMap4;
uniform sampler2D u_ShadowMap5;
uniform sampler2D u_ShadowMap6;
uniform sampler2D u_ShadowMap7;
uniform sampler2D u_ShadowMap8;
uniform sampler2D u_ShadowMap9;
uniform sampler2D u_ShadowMap10;
uniform sampler2D u_ShadowMap11;
uniform sampler2D u_ShadowMap12;
uniform sampler2D u_ShadowMap13;
uniform sampler2D u_ShadowMap14;
uniform sampler2D u_ShadowMap15;
uniform sampler2D u_ShadowMap16;
uniform sampler2D u_ShadowMap17;
uniform sampler2D u_ShadowMap18;
uniform sampler2D u_ShadowMap19;
uniform sampler2D u_ShadowMap20;
uniform sampler2D u_ShadowMap21;
uniform sampler2D u_ShadowMap22;
uniform sampler2D u_ShadowMap23;
uniform sampler2D u_ShadowMap24;
uniform sampler2D u_ShadowMap25;
uniform sampler2D u_ShadowMap26;
uniform sampler2D u_ShadowMap27;
uniform sampler2D u_ShadowMap28;
uniform sampler2D u_ShadowMap29;
uniform sampler2D u_ShadowMap30;
uniform sampler2D u_ShadowMap31;

// Cube map shadow textures for point lights (up to 8)
uniform samplerCube u_ShadowCubeMap0;
uniform samplerCube u_ShadowCubeMap1;
uniform samplerCube u_ShadowCubeMap2;
uniform samplerCube u_ShadowCubeMap3;
uniform samplerCube u_ShadowCubeMap4;
uniform samplerCube u_ShadowCubeMap5;
uniform samplerCube u_ShadowCubeMap6;
uniform samplerCube u_ShadowCubeMap7;

// Material properties
uniform vec4 u_AlbedoColor;
uniform vec4 u_EmissiveColor;
uniform vec4 u_MaterialParams1; // metallic, roughness, normalScale, emissiveStrength
uniform vec4 u_MaterialParams2; // alphaCutoff, aoStrength, heightScale, unused
uniform vec4 u_TextureFlags;    // useAlbedo, useMetallicRoughness, useNormal, useEmissive
uniform vec4 u_TintColor;
uniform bool u_ReceiveShadow;

// Light data structure (matches GPULightData in Light.hpp)
struct Light {
    vec4 positionOrDirection; // w=0 for directional, w=1 for point/spot
    vec4 direction;           // xyz=direction for spot/directional lights, w=unused
    vec4 color;               // RGB + intensity in w
    vec4 params;              // x=range, y=innerConeAngle, z=outerConeAngle, w=attenuation
    vec4 flags;               // x=type, y=castShadows, z=shadowMapIndex, w=unused
};

// Shadow map data structure
struct ShadowMap {
    mat4 lightSpaceMatrix;   // Light space transformation matrix
    vec4 shadowParams;       // x=bias, y=normalBias, z=shadowBlur, w=shadowOpacity
    vec4 shadowParams2;      // x=shadowResolution, y=isCubeMap, z=lightRange (for cube maps), w=unused
};

// Cascaded shadow map data structure
struct CascadedShadowMap {
    mat4 cascadeMatrices[8]; // Light space matrix for each cascade
    vec4 cascadeSplits;      // Split distances for cascades 0-3 (x, y, z, w)
    vec4 cascadeSplits2;     // Split distances for cascades 4-7 (x, y, z, w)
    vec4 cascadeParams;      // x=cascadeCount, y=bias, z=normalBias, w=baseShadowMapIndex
};

// Light uniform buffer (std140 layout, binding point 0)
layout(std140) uniform LightData {
    Light lights[16];
    ShadowMap shadowMaps[8];
    CascadedShadowMap cascadedShadowMaps[8];
    vec4 ambientLight;       // RGB + intensity
    vec4 lightCounts;        // x=numLights, y=numShadowMaps, z=numCascadedShadowMaps, w=unused
} u_Lights;

out vec4 FragColor;

const float PI = 3.14159265359;

// Normal mapping
vec3 getNormalFromMap() {
    if (u_TextureFlags.z < 0.5) {
        return normalize(v_Normal);
    }

    vec3 tangentNormal = texture(u_NormalTexture, v_TexCoord).xyz * 2.0 - 1.0;
    tangentNormal.xy *= u_MaterialParams1.z; // normalScale

    // Construct TBN matrix
    vec3 Q1 = dFdx(v_WorldPos);
    vec3 Q2 = dFdy(v_WorldPos);
    vec2 st1 = dFdx(v_TexCoord);
    vec2 st2 = dFdy(v_TexCoord);

    vec3 N = normalize(v_Normal);
    vec3 T = normalize(Q1 * st2.t - Q2 * st1.t);
    vec3 B = -normalize(cross(N, T));
    mat3 TBN = mat3(T, B, N);

    return normalize(TBN * tangentNormal);
}

// PBR functions (same as p_b_r.frag)
float DistributionGGX(vec3 N, vec3 H, float roughness) {
    float a = roughness * roughness;
    float a2 = a * a;
    float NdotH = max(dot(N, H), 0.0);
    float NdotH2 = NdotH * NdotH;
    float nom = a2;
    float denom = (NdotH2 * (a2 - 1.0) + 1.0);
    denom = PI * denom * denom;
    return nom / denom;
}

float GeometrySchlickGGX(float NdotV, float roughness) {
    float r = (roughness + 1.0);
    float k = (r * r) / 8.0;
    float nom = NdotV;
    float denom = NdotV * (1.0 - k) + k;
    return nom / denom;
}

float GeometrySmith(vec3 N, vec3 V, vec3 L, float roughness) {
    float NdotV = max(dot(N, V), 0.0);
    float NdotL = max(dot(N, L), 0.0);
    float ggx2 = GeometrySchlickGGX(NdotV, roughness);
    float ggx1 = GeometrySchlickGGX(NdotL, roughness);
    return ggx1 * ggx2;
}

vec3 fresnelSchlick(float cosTheta, vec3 F0) {
    return F0 + (1.0 - F0) * pow(clamp(1.0 - cosTheta, 0.0, 1.0), 5.0);
}

// Sample shadow cube map based on index
float sampleShadowCubeMap(int cubeMapIndex, vec3 direction) {
    if (cubeMapIndex == 0) return texture(u_ShadowCubeMap0, direction).r;
    if (cubeMapIndex == 1) return texture(u_ShadowCubeMap1, direction).r;
    if (cubeMapIndex == 2) return texture(u_ShadowCubeMap2, direction).r;
    if (cubeMapIndex == 3) return texture(u_ShadowCubeMap3, direction).r;
    if (cubeMapIndex == 4) return texture(u_ShadowCubeMap4, direction).r;
    if (cubeMapIndex == 5) return texture(u_ShadowCubeMap5, direction).r;
    if (cubeMapIndex == 6) return texture(u_ShadowCubeMap6, direction).r;
    if (cubeMapIndex == 7) return texture(u_ShadowCubeMap7, direction).r;
    return 1.0;
}

// Sample shadow map based on index
float sampleShadowMap(int shadowMapIndex, vec2 uv) {
    if (shadowMapIndex == 0) return texture(u_ShadowMap0, uv).r;
    if (shadowMapIndex == 1) return texture(u_ShadowMap1, uv).r;
    if (shadowMapIndex == 2) return texture(u_ShadowMap2, uv).r;
    if (shadowMapIndex == 3) return texture(u_ShadowMap3, uv).r;
    if (shadowMapIndex == 4) return texture(u_ShadowMap4, uv).r;
    if (shadowMapIndex == 5) return texture(u_ShadowMap5, uv).r;
    if (shadowMapIndex == 6) return texture(u_ShadowMap6, uv).r;
    if (shadowMapIndex == 7) return texture(u_ShadowMap7, uv).r;
    if (shadowMapIndex == 8) return texture(u_ShadowMap8, uv).r;
    if (shadowMapIndex == 9) return texture(u_ShadowMap9, uv).r;
    if (shadowMapIndex == 10) return texture(u_ShadowMap10, uv).r;
    if (shadowMapIndex == 11) return texture(u_ShadowMap11, uv).r;
    if (shadowMapIndex == 12) return texture(u_ShadowMap12, uv).r;
    if (shadowMapIndex == 13) return texture(u_ShadowMap13, uv).r;
    if (shadowMapIndex == 14) return texture(u_ShadowMap14, uv).r;
    if (shadowMapIndex == 15) return texture(u_ShadowMap15, uv).r;
    if (shadowMapIndex == 16) return texture(u_ShadowMap16, uv).r;
    if (shadowMapIndex == 17) return texture(u_ShadowMap17, uv).r;
    if (shadowMapIndex == 18) return texture(u_ShadowMap18, uv).r;
    if (shadowMapIndex == 19) return texture(u_ShadowMap19, uv).r;
    if (shadowMapIndex == 20) return texture(u_ShadowMap20, uv).r;
    if (shadowMapIndex == 21) return texture(u_ShadowMap21, uv).r;
    if (shadowMapIndex == 22) return texture(u_ShadowMap22, uv).r;
    if (shadowMapIndex == 23) return texture(u_ShadowMap23, uv).r;
)";

constexpr const char* skeletal_frag_chunk1 = R"(
    if (shadowMapIndex == 24) return texture(u_ShadowMap24, uv).r;
    if (shadowMapIndex == 25) return texture(u_ShadowMap25, uv).r;
    if (shadowMapIndex == 26) return texture(u_ShadowMap26, uv).r;
    if (shadowMapIndex == 27) return texture(u_ShadowMap27, uv).r;
    if (shadowMapIndex == 28) return texture(u_ShadowMap28, uv).r;
    if (shadowMapIndex == 29) return texture(u_ShadowMap29, uv).r;
    if (shadowMapIndex == 30) return texture(u_ShadowMap30, uv).r;
    if (shadowMapIndex == 31) return texture(u_ShadowMap31, uv).r;
    return 1.0;
}

// Calculate shadow factor for cube map (point lights)
float calculateShadowCube(int cubeMapIndex, vec3 lightPos, vec3 worldPos, vec3 normal, float bias, float shadowBlur, float shadowOpacity, float lightRange) {
    // Calculate direction from light to fragment
    vec3 fragToLight = worldPos - lightPos;
    float currentDepth = length(fragToLight);

    // Normalize current depth to [0,1] range
    float normalizedCurrentDepth = currentDepth / lightRange;

    // Normalize direction for sampling
    vec3 sampleDir = normalize(fragToLight);

    // Sample the cube map (already stores normalized linear depth in [0,1])
    float closestDepth = sampleShadowCubeMap(cubeMapIndex, sampleDir);

    // Compare depths (both in [0,1] range)
    float shadow = (normalizedCurrentDepth - bias > closestDepth) ? 0.0 : 1.0;

    // Apply shadow opacity
    shadow = mix(1.0, shadow, shadowOpacity);

    return shadow;
}

// Calculate shadow with PCF
float calculateShadowPCF(mat4 lightSpaceMatrix, int shadowMapIndex, vec3 worldPos, vec3 normal, vec3 lightDir,
                        float bias, float normalBias, float shadowBlur, float shadowOpacity, float shadowResolution) {
    // Transform world position to light space
    vec4 fragPosLightSpace = lightSpaceMatrix * vec4(worldPos, 1.0);

    // Perform perspective divide
    vec3 projCoords = fragPosLightSpace.xyz / fragPosLightSpace.w;

    // Transform to [0,1] range
    projCoords = projCoords * 0.5 + 0.5;

    // Check if fragment is outside light frustum
    if (projCoords.z > 1.0 || projCoords.x < 0.0 || projCoords.x > 1.0 ||
        projCoords.y < 0.0 || projCoords.y > 1.0) {
        return 1.0; // No shadow
    }

    // Get current depth
    float currentDepth = projCoords.z;

    // Apply normal bias
    float NdotL = max(dot(normal, lightDir), 0.0);
    float biasAdjusted = bias + normalBias * sqrt(1.0 - NdotL * NdotL);

    // PCF (Percentage Closer Filtering)
    float shadow = 0.0;
    vec2 texelSize = 1.0 / vec2(shadowResolution, shadowResolution);
    int pcfRadius = int(shadowBlur);
    int pcfSamples = 0;

    for (int x = -pcfRadius; x <= pcfRadius; ++x) {
        for (int y = -pcfRadius; y <= pcfRadius; ++y) {
            vec2 offset = vec2(x, y) * texelSize;
            float pcfDepth = sampleShadowMap(shadowMapIndex, projCoords.xy + offset);
            shadow += (currentDepth - biasAdjusted > pcfDepth) ? 0.0 : 1.0;
            pcfSamples++;
        }
    }
    shadow /= float(pcfSamples);

    // Apply shadow opacity
    shadow = mix(1.0, shadow, shadowOpacity);

    return shadow;
}

// Calculate shadow (dispatches to appropriate shadow calculation method)
float calculateShadow(int shadowMapIndex, vec3 worldPos, vec3 normal, vec3 lightDir, vec3 lightPos) {
    if (shadowMapIndex < 0 || shadowMapIndex >= 8) {
        return 1.0; // No shadow
    }

    ShadowMap shadowMap = u_Lights.shadowMaps[shadowMapIndex];

    // Check if this is a cube map shadow (for point lights)
    bool isCubeMap = shadowMap.shadowParams2.y > 0.5;

    if (isCubeMap) {
        // Use cube map shadow calculation for point lights
        float lightRange = shadowMap.shadowParams2.z;
        return calculateShadowCube(shadowMapIndex, lightPos, worldPos, normal,
                                  shadowMap.shadowParams.x, shadowMap.shadowParams.z,
                                  shadowMap.shadowParams.w, lightRange);
    } else {
        // Use standard 2D shadow map calculation
        return calculateShadowPCF(shadowMap.lightSpaceMatrix, shadowMapIndex, worldPos, normal, lightDir,
                                  shadowMap.shadowParams.x, shadowMap.shadowParams.y,
                                  shadowMap.shadowParams.z, shadowMap.shadowParams.w,
                                  shadowMap.shadowParams2.x);
    }
}

void main() {
    // Sample textures
    vec4 albedo = u_AlbedoColor;
    if (u_TextureFlags.x > 0.5) {
        albedo *= texture(u_AlbedoTexture, v_TexCoord);
    }

    // Alpha test
    if (albedo.a < u_MaterialParams2.x) {
        discard;
    }

    float metallic = u_MaterialParams1.x;
    float roughness = u_MaterialParams1.y;
    if (u_TextureFlags.y > 0.5) {
        vec4 mr = texture(u_MetallicRoughnessTexture, v_TexCoord);
        metallic *= mr.b;
        roughness *= mr.g;
    }

    vec3 N = getNormalFromMap();
    vec3 V = normalize(v_ViewDir);

    vec3 F0 = vec3(0.04);
    F0 = mix(F0, albedo.rgb, metallic);

    vec3 Lo = vec3(0.0);
    int numLights = int(u_Lights.lightCounts.x);

    for (int i = 0; i < numLights && i < 16; ++i) {
        Light light = u_Lights.lights[i];
        int lightType = int(light.flags.x);
        bool castsShadows = light.flags.y > 0.5;
        int shadowMapIndex = int(light.flags.z);

        vec3 L;
        float attenuation = 1.0;

        // Calculate light direction and attenuation based on type
        if (lightType == 0) {
            // Directional light
            L = normalize(-light.direction.xyz);
        } else if (lightType == 1) {
            // Point light
            vec3 lightPos = light.positionOrDirection.xyz;
            vec3 lightDir = lightPos - v_WorldPos;
            float distance = length(lightDir);
            L = normalize(lightDir);

            float range = light.params.x;
            float attenuationExp = light.params.w;

            // Distance-based attenuation with configurable exponent
            // Using inverse square law as base, modified by attenuation exponent
            float distanceFactor = distance / range;
            attenuation = 1.0 / (1.0 + pow(distanceFactor, attenuationExp));

            // Smooth cutoff at range boundary
            attenuation *= smoothstep(1.0, 0.5, distanceFactor);
        } else if (lightType == 2) {
            // Spot light
            vec3 lightPos = light.positionOrDirection.xyz;
            vec3 lightDir = lightPos - v_WorldPos;
            float distance = length(lightDir);
            L = normalize(lightDir);

            vec3 spotDir = normalize(light.direction.xyz);
            float theta = dot(L, -spotDir);
            float innerCutoff = light.params.y; // Already cosine
            float outerCutoff = light.params.z; // Already cosine

            // Calculate spot intensity with smooth falloff
            // Use max to prevent division by zero when inner and outer cutoffs are too close
            float epsilon = max(innerCutoff - outerCutoff, 0.0001);
            float spotIntensity = clamp((theta - outerCutoff) / epsilon, 0.0, 1.0);
            // Apply smooth curve for better visual falloff
            spotIntensity = smoothstep(0.0, 1.0, spotIntensity);

            float range = light.params.x;
            float attenuationExp = light.params.w;

            // Distance-based attenuation with configurable exponent
            float distanceFactor = clamp(distance / range, 0.0, 1.0);
            attenuation = 1.0 / (1.0 + pow(distanceFactor, attenuationExp));

            // Smooth cutoff at range boundary
            attenuation *= smoothstep(1.0, 0.5, distanceFactor);

            // Apply spot intensity to attenuation
            attenuation *= spotIntensity;
        }

)";

constexpr const char* skeletal_frag_chunk2 = R"(
        vec3 H = normalize(V + L);

        float NDF = DistributionGGX(N, H, roughness);
        float G = GeometrySmith(N, V, L, roughness);
        vec3 F = fresnelSchlick(max(dot(H, V), 0.0), F0);

        vec3 kS = F;
        vec3 kD = vec3(1.0) - kS;
        kD *= 1.0 - metallic;

        vec3 numerator = NDF * G * F;
        float denominator = 4.0 * max(dot(N, V), 0.0) * max(dot(N, L), 0.0) + 0.0001;
        vec3 specular = numerator / denominator;

        float NdotL = max(dot(N, L), 0.0);

        // Calculate shadow
        float shadow = 1.0;
        if (u_ReceiveShadow && castsShadows && shadowMapIndex >= 0) {
            // All lights with shadows use the standard shadow map path
            // (spot, omni, and directional lights all use non-cascaded shadows for now)
            vec3 lightPos = light.positionOrDirection.xyz;
            shadow = calculateShadow(shadowMapIndex, v_WorldPos, N, L, lightPos);
        }

        vec3 radiance = light.color.rgb * light.color.w * attenuation;
        Lo += (kD * albedo.rgb / PI + specular) * radiance * NdotL * shadow;
    }

    vec3 emissive = u_EmissiveColor.rgb * u_MaterialParams1.w;
    if (u_TextureFlags.w > 0.5) {
        emissive *= texture(u_EmissiveTexture, v_TexCoord).rgb;
    }

    float ao = 1.0;
    vec3 ambient = u_Lights.ambientLight.rgb * u_Lights.ambientLight.a * albedo.rgb * ao;
    vec3 color = (ambient + Lo + emissive) * u_TintColor.rgb;

    // HDR tonemapping (simple Reinhard)
    color = color / (color + vec3(1.0));

    // Gamma correction
    color = pow(color, vec3(1.0/2.2));

    FragColor = vec4(color, albedo.a);
}


)";

inline std::string get_skeletal_frag() {
    std::string result;
    result.reserve(17181);  // Pre-allocate
    result += skeletal_frag_chunk0;
    result += skeletal_frag_chunk1;
    result += skeletal_frag_chunk2;
    return result;
}

inline const char* skeletal_frag() {
    static const std::string shader = get_skeletal_frag();
    return shader.c_str();
}

constexpr const char* skeletal_vert = R"(

#version 330 core

layout(location = 0) in vec3 a_Position;
layout(location = 1) in vec3 a_Normal;
layout(location = 2) in vec2 a_TexCoord;
layout(location = 3) in vec4 a_Color;
layout(location = 4) in vec3 a_Tangent;
layout(location = 5) in vec4 a_BoneIDs;
layout(location = 6) in vec4 a_BoneWeights;

const int MAX_BONES = 128;
uniform mat4 u_BoneTransforms[MAX_BONES];
uniform bool u_UseSkinning;

uniform mat4 u_ViewProjection;
uniform mat4 u_View;
uniform mat4 u_Model;
uniform mat4 u_NormalMatrix;
uniform vec3 u_CameraPosition;

out vec3 v_WorldPos;
out vec3 v_ViewPos;
out vec3 v_Normal;
out vec2 v_TexCoord;
out vec4 v_Color;
out vec3 v_ViewDir;

void main() {
    vec4 localPos = vec4(a_Position, 1.0);
    vec3 localNormal = a_Normal;

    // Apply skeletal animation if enabled
    if (u_UseSkinning) {
        mat4 boneTransform = mat4(0.0);
        float totalWeight = 0.0;

        // Accumulate bone transformations weighted by bone weights
        for (int i = 0; i < 4; i++) {
            int boneID = int(a_BoneIDs[i]);
            float weight = a_BoneWeights[i];

            if (boneID >= 0 && boneID < MAX_BONES && weight > 0.0) {
                boneTransform += u_BoneTransforms[boneID] * weight;
                totalWeight += weight;
            }
        }

        // Only apply bone transformation if we have valid weights
        // If totalWeight is 0, the vertex has no bone influences and should use identity
        if (totalWeight > 0.0) {
            localPos = boneTransform * localPos;
            // Transform normals using mat3 of bone transform
            localNormal = mat3(boneTransform) * localNormal;
        }
    }

    // Transform to world space (applies to both skinned and non-skinned)
    vec4 worldPos = u_Model * localPos;
    v_WorldPos = worldPos.xyz;
    v_ViewPos = (u_View * worldPos).xyz;

    // For skeletal meshes, normals are already transformed by bone matrices in local space
    // We only need to apply the model matrix (not the normal matrix) to bring them to world space
    // The normal matrix is inverse-transpose of the model matrix, which is only needed when
    // the model matrix contains non-uniform scaling. Since bone transforms are applied first,
    // we use the model matrix directly for consistency.
    v_Normal = normalize(mat3(u_Model) * localNormal);

    v_TexCoord = a_TexCoord;
    v_Color = a_Color;
    v_ViewDir = normalize(u_CameraPosition - v_WorldPos);

    gl_Position = u_ViewProjection * worldPos;
}


)";

constexpr const char* skybox_frag = R"(

#version 330 core

in vec3 v_Position;
in vec3 v_TexCoord;

// Skybox type: 0=None, 1=Color, 2=Procedural, 3=Cubemap, 4=Panoramic
uniform int u_SkyboxType;

// Color skybox
uniform vec4 u_SkyboxColor;

// Procedural skybox
uniform vec4 u_SkyTopColor;
uniform vec4 u_SkyHorizonColor;
uniform vec4 u_SkyBottomColor;

// Cubemap skybox
uniform samplerCube u_CubemapTexture;

// Panoramic skybox
uniform sampler2D u_PanoramicTexture;

out vec4 FragColor;

// Convert cartesian coordinates to spherical UV for panoramic mapping
vec2 cartesianToSpherical(vec3 dir) {
    // Normalize direction
    vec3 n = normalize(dir);
    
    // Calculate spherical coordinates
    float u = 0.5 + atan(n.z, n.x) / (2.0 * 3.14159265359);
    float v = 0.5 - asin(n.y) / 3.14159265359;
    
    return vec2(u, v);
}

void main() {
    if (u_SkyboxType == 0) {
        // None - transparent
        FragColor = vec4(0.0, 0.0, 0.0, 0.0);
    }
    else if (u_SkyboxType == 1) {
        // Solid color
        FragColor = u_SkyboxColor;
    }
    else if (u_SkyboxType == 2) {
        // Procedural gradient
        vec3 dir = normalize(v_Position);
        float height = dir.y;
        
        // Interpolate between bottom, horizon, and top colors
        vec4 color;
        if (height > 0.0) {
            // Above horizon - blend from horizon to top
            color = mix(u_SkyHorizonColor, u_SkyTopColor, height);
        } else {
            // Below horizon - blend from bottom to horizon
            color = mix(u_SkyBottomColor, u_SkyHorizonColor, height + 1.0);
        }
        
        FragColor = color;
    }
    else if (u_SkyboxType == 3) {
        // Cubemap
        FragColor = texture(u_CubemapTexture, v_TexCoord);
    }
    else if (u_SkyboxType == 4) {
        // Panoramic (equirectangular)
        vec2 uv = cartesianToSpherical(v_Position);
        FragColor = texture(u_PanoramicTexture, uv);
    }
    else {
        // Unknown type - magenta for debugging
        FragColor = vec4(1.0, 0.0, 1.0, 1.0);
    }
}


)";

constexpr const char* skybox_vert = R"(

#version 330 core

layout(location = 0) in vec3 a_Position;
layout(location = 1) in vec3 a_Normal;
layout(location = 2) in vec2 a_TexCoord;

uniform mat4 u_ViewProjection;
uniform mat4 u_View;

out vec3 v_Position;
out vec3 v_TexCoord;

void main() {
    // Use position as texture coordinates for cubemap sampling
    v_TexCoord = a_Position;
    v_Position = a_Position;
    
    // Remove translation from view matrix to keep skybox centered on camera
    mat4 viewNoTranslation = u_View;
    viewNoTranslation[3][0] = 0.0;
    viewNoTranslation[3][1] = 0.0;
    viewNoTranslation[3][2] = 0.0;
    
    // Calculate position
    vec4 pos = u_ViewProjection * vec4(a_Position, 1.0);
    
    // Set z = w to ensure skybox is always at maximum depth
    gl_Position = pos.xyww;
}


)";

constexpr const char* sprite2_d_frag = R"(

#version 330 core

in vec2 v_TexCoord;
in vec4 v_Color;

uniform sampler2D u_Texture;
uniform vec4 u_TintColor;
uniform bool u_UseTexture;

out vec4 FragColor;

void main() {
    vec4 color = v_Color * u_TintColor;
    if (u_UseTexture) {
        color *= texture(u_Texture, v_TexCoord);
    }
    FragColor = color;
}

)";

constexpr const char* sprite2_d_vert = R"(

#version 330 core

layout(location = 0) in vec3 a_Position;
layout(location = 1) in vec2 a_TexCoord;
layout(location = 2) in vec4 a_Color;

uniform mat4 u_ViewProjection;
uniform mat4 u_Model;

out vec2 v_TexCoord;
out vec4 v_Color;

void main() {
    v_TexCoord = a_TexCoord;
    v_Color = a_Color;
    gl_Position = u_ViewProjection * u_Model * vec4(a_Position, 1.0);
}

)";

constexpr const char* sprite2_d__alpha_cutoff_frag = R"(

#version 330 core

in vec2 v_TexCoord;
in vec4 v_Color;

uniform sampler2D u_Texture;
uniform vec4 u_Modulate;
uniform float u_AlphaCutoff;
uniform bool u_UseTexture;

out vec4 FragColor;

void main() {
    vec4 color = v_Color * u_Modulate;

    if (u_UseTexture) {
        vec4 texColor = texture(u_Texture, v_TexCoord);
        color *= texColor;

        // Alpha cutoff test
        if (u_AlphaCutoff > 0.0 && color.a < u_AlphaCutoff) {
            discard;
        }
    }

    FragColor = color;
}

)";

constexpr const char* sprite2_d__alpha_cutoff_vert = R"(

#version 330 core

layout(location = 0) in vec3 a_Position;
layout(location = 1) in vec2 a_TexCoord;
layout(location = 2) in vec4 a_Color;

uniform mat4 u_ViewProjection;
uniform mat4 u_Model;

out vec2 v_TexCoord;
out vec4 v_Color;

void main() {
    v_TexCoord = a_TexCoord;
    v_Color = a_Color;
    gl_Position = u_ViewProjection * u_Model * vec4(a_Position, 1.0);
}

)";

constexpr const char* sprite3_d_frag = R"(

#version 330 core

in vec2 v_TexCoord;
in vec4 v_Color;
in vec3 v_WorldPos;

uniform sampler2D u_Texture;
uniform vec4 u_Modulate;
uniform float u_AlphaCutoff;
uniform bool u_UseTexture;

out vec4 FragColor;

void main() {
    vec4 color = v_Color * u_Modulate;

    if (u_UseTexture) {
        vec4 texColor = texture(u_Texture, v_TexCoord);
        color *= texColor;

        // Alpha cutoff test
        if (u_AlphaCutoff > 0.0 && color.a < u_AlphaCutoff) {
            discard;
        }
    }

    FragColor = color;
}

)";

constexpr const char* sprite3_d_vert = R"(

#version 330 core

layout(location = 0) in vec3 a_Position;
layout(location = 1) in vec3 a_Normal;
layout(location = 2) in vec2 a_TexCoord;
layout(location = 3) in vec4 a_Color;

uniform mat4 u_ViewProjection;
uniform mat4 u_Model;

out vec2 v_TexCoord;
out vec4 v_Color;
out vec3 v_WorldPos;

void main() {
    vec4 worldPos = u_Model * vec4(a_Position, 1.0);
    v_WorldPos = worldPos.xyz;
    v_TexCoord = a_TexCoord;
    v_Color = a_Color;
    gl_Position = u_ViewProjection * worldPos;
}

)";

constexpr const char* standard3_d_frag = R"(

#version 330 core

in vec3 v_Position;
in vec3 v_Normal;
in vec2 v_TexCoord;
in vec4 v_Color;

uniform sampler2D u_Texture;
uniform vec4 u_TintColor;
uniform bool u_UseTexture;

out vec4 FragColor;

void main() {
    vec3 normal = normalize(v_Normal);
    vec3 lightDir = normalize(vec3(0.5, 1.0, 0.3)); // Simple directional light
    float diff = max(dot(normal, lightDir), 0.0);
    vec3 lighting = vec3(0.3) + vec3(0.7) * diff; // Ambient + diffuse

    vec4 baseColor = v_Color * u_TintColor;
    if (u_UseTexture) {
        baseColor *= texture(u_Texture, v_TexCoord);
    }

    FragColor = vec4(baseColor.rgb * lighting, baseColor.a);
}

)";

constexpr const char* standard3_d_vert = R"(

#version 330 core

layout(location = 0) in vec3 a_Position;
layout(location = 1) in vec3 a_Normal;
layout(location = 2) in vec2 a_TexCoord;
layout(location = 3) in vec4 a_Color;

uniform mat4 u_ViewProjection;
uniform mat4 u_Model;
uniform mat4 u_NormalMatrix;

out vec3 v_Position;
out vec3 v_Normal;
out vec2 v_TexCoord;
out vec4 v_Color;

void main() {
    vec4 worldPos = u_Model * vec4(a_Position, 1.0);
    v_Position = worldPos.xyz;
    v_Normal = mat3(u_NormalMatrix) * a_Normal;
    v_TexCoord = a_TexCoord;
    v_Color = a_Color;
    gl_Position = u_ViewProjection * worldPos;
}

)";

constexpr const char* text_frag = R"(

#version 330 core

in vec2 v_TexCoord;
in vec4 v_Color;

uniform sampler2D u_FontAtlas;

out vec4 FragColor;

void main() {
    // Sample the font atlas (single channel)
    float alpha = texture(u_FontAtlas, v_TexCoord).r;
    FragColor = vec4(v_Color.rgb, v_Color.a * alpha);
}

)";

constexpr const char* text_vert = R"(

#version 330 core

layout(location = 0) in vec3 a_Position;
layout(location = 1) in vec3 a_Normal;
layout(location = 2) in vec2 a_TexCoord;
layout(location = 3) in vec4 a_Color;

uniform mat4 u_ViewProjection;

out vec2 v_TexCoord;
out vec4 v_Color;

void main() {
    v_TexCoord = a_TexCoord;
    v_Color = a_Color;
    gl_Position = u_ViewProjection * vec4(a_Position, 1.0);
}

)";

constexpr const char* text3d_frag = R"(

#version 330 core

in vec2 v_TexCoord;
in vec4 v_Color;

uniform sampler2D u_FontAtlas;
uniform vec4 u_TextColor;

out vec4 FragColor;

void main() {
    // Sample the font atlas (single channel for alpha)
    float alpha = texture(u_FontAtlas, v_TexCoord).r;

    // Discard fully transparent pixels to avoid depth buffer issues
    if (alpha < 0.01) {
        discard;
    }

    // Combine text color with vertex color and font alpha
    vec4 finalColor = v_Color * u_TextColor;
    FragColor = vec4(finalColor.rgb, finalColor.a * alpha);
}

)";

constexpr const char* text3d_vert = R"(

#version 330 core

layout(location = 0) in vec3 a_Position;
layout(location = 1) in vec3 a_Normal;
layout(location = 2) in vec2 a_TexCoord;
layout(location = 3) in vec4 a_Color;

uniform mat4 u_ViewProjection;
uniform mat4 u_Model;

out vec2 v_TexCoord;
out vec4 v_Color;

void main() {
    vec4 worldPos = u_Model * vec4(a_Position, 1.0);
    v_TexCoord = a_TexCoord;
    v_Color = a_Color;
    gl_Position = u_ViewProjection * worldPos;
}

)";

constexpr const char* unlit_frag = R"(

#version 330 core

in vec2 v_TexCoord;
in vec4 v_Color;

uniform sampler2D u_Texture;
uniform vec4 u_TintColor;
uniform bool u_UseTexture;
uniform vec4 u_UVRect;  // (min_u, min_v, max_u, max_v)

out vec4 FragColor;

void main() {
    vec4 color = v_Color * u_TintColor;
    if (u_UseTexture) {
        // Apply UV rect transformation
        vec2 uv = v_TexCoord;
        uv = mix(u_UVRect.xy, u_UVRect.zw, uv);

        vec4 texColor = texture(u_Texture, uv);
        color *= texColor;
    }

    // Ensure we output something visible
    if (color.a < 0.01) {
        discard;
    }

    FragColor = color;
}

)";

constexpr const char* unlit_vert = R"(

#version 330 core

layout(location = 0) in vec3 a_Position;
layout(location = 1) in vec2 a_TexCoord;
layout(location = 2) in vec4 a_Color;

uniform mat4 u_ViewProjection;
uniform mat4 u_Model;

out vec2 v_TexCoord;
out vec4 v_Color;

void main() {
    v_TexCoord = a_TexCoord;
    v_Color = a_Color;
    gl_Position = u_ViewProjection * u_Model * vec4(a_Position, 1.0);
}

)";

constexpr const char* wireframe_frag = R"(

#version 330 core

in vec4 v_Color;

uniform vec4 u_TintColor;

out vec4 FragColor;

void main() {
    FragColor = v_Color * u_TintColor;
}

)";

constexpr const char* wireframe_vert = R"(

#version 330 core

layout(location = 0) in vec3 a_Position;
layout(location = 1) in vec3 a_Normal;
layout(location = 2) in vec2 a_TexCoord;
layout(location = 3) in vec4 a_Color;

uniform mat4 u_ViewProjection;
uniform mat4 u_Model;

out vec4 v_Color;

void main() {
    v_Color = a_Color;
    gl_Position = u_ViewProjection * u_Model * vec4(a_Position, 1.0);
}

)";

} // namespace OpenGL

} // namespace GeneratedShaders
} // namespace lupine
